config/routes.rb
Rails.application.routes.draw do

  root 'teams#index'

  resources :teams do
    resources :items
    resources :characters
    member do
      get :draw_treasure
      get :draw_monster
    end
  end
  devise_for :users
end

app/models/character.rb
class Character < ActiveRecord::Base
  belongs_to :team
  validates :name, presence: :true

  def level
    lvl = LevelCalculator.new(experience, 0).level
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  has_many :teams, through: :team_items
  has_many :team_items
  paginates_per 20
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :user
  belongs_to :team
end

app/models/monster.rb
class Monster < ActiveRecord::Base
  self.table_name = 'monster'
end

app/models/team.rb
class Team < ActiveRecord::Base
  has_many :characters, dependent: :destroy
  has_many :items, through: :team_items
  has_many :team_items
  has_many :users, through: :memberships
  has_many :memberships
  validates :name, presence: :true
  alias_method :members, :users

  def to_s
    name
  end

  def member?(user)
    memberships.include?(user)
  end

  def level
    return 1 if characters.empty?
    average_team_level
  end


private

  def average_team_level
    level_sum = 0
    characters.each {|character| level_sum += character.level }
    (level_sum.to_f/characters.size).round
  end

end

app/models/team_item.rb
class TeamItem < ActiveRecord::Base
  belongs_to :team
  belongs_to :item
end

app/models/treasure.rb
class Treasure
  attr_accessor :items, :money

  def initialize(items, money)
    @items = items
    @money = money
  end

  def worth
    worth = money
    items.each { |item| worth += item.price }
    worth
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?
  has_many :teams, through: :memberships
  has_many :memberships

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :authenticate_user!

  decent_configuration do
    strategy DecentExposure::StrongParametersStrategy
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  expose(:character, attributes: :character_params)
  expose(:characters) { team.characters }
  expose(:team)

  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    if character.save
      redirect_to(team_characters_path(team))
    else
      render :new
    end
  end

  def update
    if character.save
      redirect_to(team_character_path(team, character))
    else
      render :edit
    end
  end

  def destroy
    character.destroy && redirect_to(team_characters_path(team))
  end

  private

  def character_params
    params.require(:character).permit(:name, :experience, :team_id)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  expose(:item, attributes: :team_params)
  expose(:team)
  expose(:items) { team.items.page(params[:page]) }
  expose(:item)
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  expose(:team, attributes: :team_params)
  expose(:teams) { current_user.teams }
  expose(:treasure) { TreasureDraw.new(level).call }
  expose(:experience) { EncounterExperience.new(team.level, level).call }
  expose(:monster_draw) { MonsterDraw.new(draw_monster_level).call }
  expose(:level) { params[:level].to_i }
  expose(:draw_monster_level) { params[:draw_monster][:level].to_i }

  def draw_monster
  end

  def draw_treasure
    AssignTreasureToTeam.new(treasure, team).call
    AssignExperienceToTeam.new(experience, team).call
  end

  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    team.members << current_user
    if team.save
      redirect_to(teams_path)
    else
      render :new
    end
  end

  def update
    if team.save
      redirect_to(teams_path)
    else
      render :edit
    end
  end

  def destroy
    team.destroy && redirect_to(teams_path)
  end

  private

  def team_params
    params.require(:team).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/characters/_form.html.haml
= simple_form_for([team, character]) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :experience
    = f.association :team

  .form-actions
    = f.button :submit, class: 'btn btn-success'

app/views/characters/edit.html.haml
%h1 Editing character

= render 'form'

.bttn-group
= link_to 'Show', team_character_path(team, character), class: 'btn btn-default'
= link_to 'Back', team_characters_path(team), class: 'btn btn-default'

app/views/characters/index.html.haml
%h1 Listing characters

%table
  %thead
    %tr
      %th Name
      %th Experience
      %th Team
      %th
      %th
      %th

  %tbody
    - characters.each do |character|
      %tr
        %td= character.name
        %td= character.experience
        %td= character.team
        %td= link_to 'Show', team_character_path(team, character), class: 'btn btn-default'
        %td= link_to 'Edit', edit_team_character_path(team, character), class: 'btn btn-primary'
        %td= link_to 'Destroy', team_character_path(team, character), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'

%br

= link_to 'New Character', new_team_character_path(team, character), class: 'btn btn-success'

app/views/characters/new.html.haml
%h1 New character

= render 'form'

= link_to 'Back', team_characters_path(team), class: 'btn btn-default'

app/views/characters/show.html.haml
%p#notice= notice

%p
  %b Name:
  = character.name
%p
  %b Experience:
  = character.experience
%p
  %b Team:
  = character.team

= link_to 'Edit', edit_team_character_path(team, character), class: 'btn btn-primary'
= link_to 'Back', team_characters_path(team), class: 'btn btn-default'

app/views/draw/draw_monster.html.haml
.container
  .row
    .col-md-12
      .row
        .col-md-5
          %h3
            = monster_draw[:quantity]
            = monster_draw[:monster].decorate.name_pluralize(monster_draw[:quantity])
        .col-md-7
          %h3
            = link_to 'Success', draw_treasure_path(team, level: draw_monster_level), class: 'btn btn-success'
            = link_to 'Failure', team, class: 'btn btn-danger'
  .well
    .monster_description
      .row
        .col-md-12
          !=monster_draw[:monster].full_text

app/views/items/index.html.haml
%p#notice= notice

.container
  .row
    .col-md-10
      %h2 #{team.name.upcase} - ITEMS
    .col-md-2.team_money
      %h4 Balance: #{number_with_delimiter(team.money, delimiter: " ")} gp
  .row
    .col-md-12.hr
  .well.character_list
    .row
      .col-md-5
      .col-md-7
        = paginate(items)
    .row.table_title
      .col-md-4
        NAME
      .col-md-4
        CATEGORY
      .col-md-2
        CASTER LVL
      .col-md-2.price_position
        PRICE (gp)
    - items.each do |item|
      .row
        .col-md-4
          = link_to item.name, team_item_path(team, item)
        .col-md-4
          = item.category
        .col-md-2
          = item.caster_level
        .col-md-2.price_position
          = number_with_delimiter(item.price, delimiter: " ")
    .row
      .col-md-5
      .col-md-7
        = paginate(items)

  .row
    .col-md-12
      = link_to 'Back', team_path(team), class: 'btn btn-default'

app/views/items/show.html.haml
%p#notice= notice

.container
  .row
    .col-md-10
      %h2= item.name.upcase
    .col-md-2.team_money
      %h4 Price: #{number_with_delimiter(item.price, delimiter: " ")} gp
  .row
    .col-md-12.hr
  .well.character_list
    != item.full_text
  .row
    .col-md-12
      = link_to 'Back', team_items_path(team), class: 'btn btn-default'

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Dungeon Explorer'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Dungeon Explorer'}"}
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield